### ISSUE TITLE
Getting this error when I try to use 'dd' to delete a line

### ISSUE THREAD

**Issue by BeardedDonut** [Israiloff/lvim-java-ide#1]
First, 
I'd like to thank you, it's amazing project. Honestly, I'm quite new to lvim/neovim and this was the only guide that I could follow and end up having a fully working java environment. Thanks a ton!

I tried to use `dd` to remove a line and got this error:
```
Error detected while processing function provider#clipboard#Call[9]..function provider#clipboard#Call[6]..13[15]..<SNR>37_try_cmd:
line    1:
E475: Invalid value for argument cmd: 'cb' is not executable
```
Do you know how I can resolve this?

**Comment by Israiloff** [comment]
Hi there! 
I think you've got a problem with a "cb" clipboard manager (I think it's missing). To solve this problem for now you need to install a "cb" manager or just remove the following line from `config.lua` file: 

```
require("local.clipboard")
```

![Screenshot 2024-04-18 191327](https://github.com/Israiloff/lvim-java-ide/assets/35844075/a090dc20-58b1-448e-b110-cb989a5e3af8)

**Comment by Israiloff** [comment]
Here you go! The solution was easier than I thought)
